src/Entity/Products.php
<?php

namespace App\Entity;

use App\Repository\ProductsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductsRepository::class)
 */
class Products
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $seller;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $model;

    /**
     * @ORM\Column(type="integer")
     */
    private $product_id;

    /**
     * @ORM\ManyToMany(targetEntity=SellersProducts::class, mappedBy="Sellers")
     */
    private $sellersProducts;

    public function __construct()
    {
        $this->sellersProducts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getSeller(): ?string
    {
        return $this->seller;
    }

    public function setSeller(string $seller): self
    {
        $this->seller = $seller;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(string $model): self
    {
        $this->model = $model;

        return $this;
    }

    public function getProductId(): ?int
    {
        return $this->product_id;
    }

    public function setProductId(int $product_id): self
    {
        $this->product_id = $product_id;

        return $this;
    }

    /**
     * @return Collection<int, SellersProducts>
     */
    public function getSellersProducts(): Collection
    {
        return $this->sellersProducts;
    }

    public function addSellersProduct(SellersProducts $sellersProduct): self
    {
        if (!$this->sellersProducts->contains($sellersProduct)) {
            $this->sellersProducts[] = $sellersProduct;
            $sellersProduct->addSeller($this);
        }

        return $this;
    }

    public function removeSellersProduct(SellersProducts $sellersProduct): self
    {
        if ($this->sellersProducts->removeElement($sellersProduct)) {
            $sellersProduct->removeSeller($this);
        }

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Entity\Products;
use App\Repository\ProductsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\Session;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;


class CartController extends AbstractController
{
    public $session;
    public $goods=[];
    public $gids=[];
    public $counts;
    public $combine;
    public $cart=[];
    public $items;
    public $total;
    public $product_id;
    public $total_price;
	public $totalcnt;
	
   public function __construct() {
       $this->session = new Session();
    }

    /**
     * @Route("/cart", name = "app_cart")
     * @Method("POST")
     */
    public function show(ProductsRepository $repository): Response
    {
        $this->goods = $this->session->get('goods');
        $this->counts = $this->session->get('counts');

        if (isset($this->goods)) {
            foreach ($this->goods as $key => $prd_id) {
                if ($prd_id > 0) {
                    $this->gids[] = $repository->findSelectProduct(intval($prd_id));

                    $prc = $repository->getPriceItem($prd_id);
                    if (isset($this->counts)) {
                        $this->total += $prc[0]['price'] * $this->counts[$key];
                        $this->totalcnt += $this->counts[$key];
                        $this->session->set('total', $this->total);
                        $this->session->set('totalcnt', $this->totalcnt);
                    }
                }
            }
        }

        return $this->render('cart/cart.html.twig', [
            'goods' => $this->goods,
            'gids' => $this->gids,
            'counts' => $this->counts,
            'total' => $this->total
        ]);
    }

    /**
     * @Route("/cart/delete", name="app_cart_delete")
     */
    public function delete(Request $request): Response
    {
        $d = $request->query->get('d');
        $this->product_id = $d;
        $this->counts = $this->session->get('counts');
        $this->goods = $this->session->get('goods');

        $i = 0;
        while ($this->goods[$i] != $this->product_id && $i < count($this->goods)) $i++;
        // $this->goods[0] = 0;
        $this->counts[$i] = 0;
        $this->session->set('goods', $this->goods);
        $this->session->set('counts', $this->counts);

        return $this->redirectToRoute('app_cart');
    }

    /**
     * @Route("/cart/add", name="app_cart_add")
     */

    public function add(Request $request, ProductsRepository $repository): Response
    {
        $p = $request->query->get('p');
        if ($p > 0) {
            $this->product_id = $p;

            $this->goods = $this->session->get('goods');
            $this->counts = $this->session->get('counts');
            $i = 0;
            if (isset($this->goods)) $cnt = count($this->goods);
            else $cnt = 1;
            if (isset($this->goods)) {
                foreach ($this->goods as $item) {
                    if ($item == $this->product_id) {
                        $this->counts[$i]++;
                        break;
                    } else if ($i + 1 == $cnt) {
                        $this->goods[$i + 1] = $this->product_id;
                        $this->counts[$i + 1] = 1;
                    }
                    $i++;
                }
            } else {
                $this->goods[0] = $this->product_id;
                $this->counts[0] = 1;
            }
            $this->session->set('goods', $this->goods);
            $this->session->set('counts', $this->counts);

        }
        return $this->redirectToRoute('app_cart');
    }

    /**
     * @Route("/cart/update", name="app_cart_update")
     */

    public function update(): Response
    {
        if (isset($_POST['clear'])) {
            $this->session->remove('goods');
            $this->session->remove('counts');
        }

        if (isset($_POST['update'])) {
            $this->counts = $this->session->get('counts');
            $this->goods = $this->session->get('goods');

            foreach ($_POST['amount'] as $item_id => $count_item) {

                for ($i = 0; $i < count($this->goods); $i++)
                    if ($this->goods[$i] == intval($item_id)) {
                        $this->counts[$i] = intval($count_item);
                    }
            }
            $this->session->set('counts', $this->counts);
        }
        return $this->redirectToRoute('app_cart');
    }
}

templates/cart/cart.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="Middle Middle_top">
    <div class="Middle-top">
        <div class="wrap">
            <div class="Middle-header">
                <h1 class="Middle-title">Корзина</h1>
                <ul class="breadcrumbs Middle-breadcrumbs">
                    <li class="breadcrumbs-item"><a href="{{ path('app_index') }}">Главная</a></li>
                    <li class="breadcrumbs-item breadcrumbs-item_current"><span>Корзина</span></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="Section">
        <div class="wrap">
            <form class="form Cart" action="{{ path('app_cart_update') }}" method="post">
                {% set i = 0 %}
                {% for gid in gids %}
                    {% if counts is not null %}
                 {% if counts [i] > 0 %}

                <div class="Cart-product">
                    <div class="Cart-block Cart-block_row">
                        <div class="Cart-block Cart-block_pict">
                            <a class="Cart-pict" href="{{ path('app_product_show') }}?p={{ gid.0.productId }}"><img class="Cart-img" src="assets/img/content/home/card.jpg" alt="card.jpg"/></a>
                        </div>
                        <div class="Cart-block Cart-block_info"><a class="Cart-title" href="{{ path('app_product_show') }}?p={{ gid.0.productId }}">{{ gid.0.title }}</a>
                            <div class="Cart-desc">Это супер ноутбук, 3 гб. 4 ядра   {{ gid.0.productId }}
                            </div>
                        </div>
                        <div class="Cart-block Cart-block_price">
                            <div class="Cart-price">{{ gid.0.price }}$
                            </div>

                        </div>
                    </div>
                    <div class="Cart-block Cart-block_row">
                        <div class="Cart-block Cart-block_seller">
                            <!-- - var options = setOptions(items, ['value', 'selected', 'disabled']);-->
                            <select class="form-select">
                                <option value="good" selected="selected">shop good
                                </option>
                                <option value="kke">shop kke
                                </option>
                                <option value="sssssl">market sssssl
                                </option>
                            </select>
                        </div>
                        <div class="Cart-block Cart-block_amount">
                            <div class="Cart-amount">
                                <div class="Amount">
                                    <button class="Amount-remove" type="button">
                                    </button>
                                    <input class="Amount-input form-input" name="amount[{{gid.0.productId}}]" type="text" value="{{ counts [i] }}" />
                                    <button class="Amount-add" type="button">
                                    </button>

                                </div>
                            </div>
                        </div>
                        <div class="Cart-block Cart-block_delete">
                            <a class="Cart-delete" href="{{ path('app_cart_delete') }}?d={{gid.0.productId}}"><img src="assets/img/icons/card/delete.svg" alt="delete.svg"/></a>
                        </div>

                    </div>
                </div>
                     {{ gid.0.price * counts[i] }}
                    {% endif %}
                    {% endif %}
                    {% set i = i + 1 %}

                {% endfor %}

                <div class="Cart-total">
                    <div class="Cart-block Cart-block_total">
                        <strong class="Cart-title">Итого:
                        </strong><span class="Cart-price">{{ total }}$</span><span class="Cart-price_old">250.99$</span>
                    </div>
                    <div class="Cart-block">
                        <input  type="submit" class="btn btn_success btn_lg" id="clear" name="clear" value="Очистить">
                    </div>
                    <div class="Cart-block">
                    <input  type="submit" class="btn btn_success btn_lg" id="update" name="update" value="Пересчитать">
                </div>
                    <div class="Cart-block">
                        <a class="btn btn_success btn_lg" href="{{ path('app_catalog') }}">Продолжить покупки</a>
                    </div>
                    <div class="Cart-block"><a class="btn btn_success btn_lg" href="{{ path('app_order') }}">Оформить заказ</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}